### ISSUE TITLE
Screenshots should be just the app window

### ISSUE THREAD

**Issue by razzeee** [flathub/com.sudovanilla.penpot-desktop#1]
See https://docs.flathub.org/docs/for-app-authors/appdata-guidelines/quality-guidelines/#screenshots for more guidance

**Comment by SudoVanilla** [comment]
Ah that sucks. Alright, I'll update the repo later to only include window screenshots, not desktop screenshots. Thanks for letting me know and I'll read the quality guidelines more in-depth later as well.

**Comment by razzeee** [comment]
Those are suggestions, we will start to hide apps in some places on the website, but for now, nothing is happening. Even if we consider it bad practice.
